[package]
name = "rust-postgres"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
dotenv = "0.15"
serde = { version = "1" , features = ["derive"]}
serde_json ={ version = "1"}
sqlx = { version = "0.7.4", features = [ "runtime-tokio", "tls-rustls", "postgres" ] }
